name: founder_code_hr_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  geolocator:
  provider:
  connectivity_plus: ^6.1.0
  intl:
  geocoding:
  image_picker:
  http:
  shared_preferences:
  google_maps_flutter:
#  local_auth: ^2.3.0
  permission_handler:







dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true



  assets:
    - assets/

